# This is a Docker Compose configuration
# intended for development purposes only

volumes:
  db: {}

networks:
  app-network:

services:
  db:
    image: mariadb:lts
    environment:
      MARIADB_USER: bookstack
      MARIADB_PASSWORD: "password"
      MARIADB_DATABASE: bookstack
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    environment:
      APP_URL: http://localhost:${DEV_PORT:-8080}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: bookstack
      DB_PASSWORD: "password"
      DB_DATABASE: bookstack
      TEST_DATABASE_URL: mysql://bookstack-test:bookstack-test@db/bookstack-test
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MEILISEARCH_HOST: "meilisearch"
      MEILISEARCH_PORT: 7700
      MEILISEARCH_MASTER_KEY: ""
    ports:
      - 8080:80
    networks:
      - app-network
    volumes:
      - ./:/app
      - ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/dev/docker/entrypoint.app.sh
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - node
      - meilisearch
      - mailhog
  node:
    image: node:22-alpine
    working_dir: /app
    user: node
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh
    networks:
      - app-network
  meilisearch:
    image: getmeili/meilisearch:v1.9.1
    restart: on-failure
    volumes:
      - ./data/meili:/meili_data
    ports:
      - 7700:7700
    networks:
      - app-network
  mailhog:
    image: mailhog/mailhog
    ports:
      - ${DEV_MAIL_PORT:-8025}:8025
